# Generated by Django 4.2.3 on 2025-06-24 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0047_feedbackexcelupload_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('input_files', models.JSONField(blank=True, null=True)),
                ('chart_data', models.JSONField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.schedule')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.training')),
            ],
        ),
    ]
